### ISSUE TITLE
Sharing is caring

### ISSUE THREAD

**Issue by jhabdas** [andreaskeller/react-native-audioplayer#1]
Just wanted to mention @brentvatne was thinking of supporting audio in his [react-native-video](https://github.com/brentvatne/react-native-video) component. Here's some [work I've done](http://slides.com/jhabdas/streaming-audio-react-native/#/7/4) on building out an audio native with StreamingKit if it helps any. Check the `src/lib` for my audio module.

**Comment by brentvatne** [comment]
:+1:

**Comment by andreaskeller** [comment]
@jhabdas thanks for the information. the lumpen-radio project looks really interesting. I registered for your webcast. looking forward to it.

**Comment by jhabdas** [comment]
Closing this as it's not an issue. @andreaskeller I'm going to sub a PR to add `pause` and `stop` methods, borrowing from https://github.com/cymen/react-native-audioplayer.
