### ISSUE TITLE
Issues getting started

### ISSUE THREAD

**Issue by tgoldenberg** [andreaskeller/react-native-audioplayer#10]
Not sure what I'm doing wrong, but unable to get started. Getting error `Cannot read property 'play' of undefined`. Here are some screenshots that should provide more light. 

<img width="311" alt="screen shot 2015-10-17 at 11 40 02 am" src="https://cloud.githubusercontent.com/assets/10930134/10559643/08548e4a-74c4-11e5-8920-cd49470eea64.png">
<img width="251" alt="screen shot 2015-10-17 at 11 40 19 am" src="https://cloud.githubusercontent.com/assets/10930134/10559644/0d48ef90-74c4-11e5-8ef7-15a8af0f64ad.png">
<img width="687" alt="screen shot 2015-10-17 at 11 40 26 am" src="https://cloud.githubusercontent.com/assets/10930134/10559645/12084e0e-74c4-11e5-954f-043de949e51c.png">

**Comment by andreaskeller** [comment]
@tgoldenberg did you resolve your problem? you have a require statement, right?

``` javascript
var AudioPlayer = require('react-native-audioplayer');
```

did you add the `libRNAudioPlayer.a` to the **Build Phases**?
